#
# The following environment variables should be predefined:
#
# OPS_INSTALL_PATH
# OPS_COMPILER (gnu,intel,etc)
#

include $(OPS_INSTALL_PATH)/../makefiles/Makefile.common
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.mpi
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.hdf5




HEADERS=cw_kernels.h

OPS_FILES=coursework_parallel.cpp

OPS_GENERATED=coursework_parallel_ops.cpp

OTHER_FILES=


APP=coursework_parallel
MAIN_SRC=coursework_parallel

include $(OPS_INSTALL_PATH)/../makefiles/Makefile.c_app